
### Recuperar todas las peliculas
GET http://localhost:3000/movies

### Recuperar una pelicula por id
GET  http://localhost:3000/movies/dcdd0fad-a94c-4810-8acc-5f108d3b18c3

### Recuperar todas las peliculas por genero
GET http://localhost:3000/movies?genre=action

### Crear una pelicula con POST
POST http://localhost:3000/movies
Content-Type: application/json

{
    "title":"The godfather",
    "genre": [
        "Crime",
        "Drama"
    ],
    "director":"Francis Ford Coppola",
    "year": 1975,
    "duration": 175,
    "rate": 0,
    "poster": "https://img.fruugo.com/product/4/49/14441494_max.jpg"
}
### Actualizar una pelicula
PATCH http://localhost:3000/movies/dcdd0fad-a94c-4810-8acc-5f108d3b18c3
Content-Type: application/json

{
    "id":"2",
    "year": 1999
}